name: fixify_app
description: Fixify - Simplifying Technician Selection for Bangladeshis

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_custom_clippers: ^2.1.0
  get: ^4.6.5
  animated_toggle_switch: ^0.6.2
  expandable_page_view: ^1.0.17
  flutter_spinkit: ^5.2.0
  image_picker: ^0.8.9
  multi_select_flutter: ^4.1.3
  day_night_time_picker: ^1.3.0
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.2
  firebase_storage: ^11.2.4
  intl: ^0.18.1
  shared_preferences: ^2.1.2
  uuid: ^3.0.7
  shimmer: ^3.0.0
  cached_network_image: ^3.2.3
  smooth_page_indicator: ^1.1.0
  animated_text_kit: ^4.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

